javac AudioPlayer.java
javac Block.java
javac CustomColor.java
javac Fire.java
javac Frame.java
javac Level.java
javac Level1.java
javac Level2.java
javac Level3.java
javac Level4.java
javac Level5.java
javac Level6.java
javac Level7.java
javac Level8.java
javac Level9.java
javac Level10.java
javac Level11.java
javac Level12.java
javac Level13.java
javac LevelWithFire.java
javac Main.java
javac Panel.java
javac Utils.java
java Main